### ISSUE TITLE
Feature request: user controllable decimal places (+ currency?)

### ISSUE THREAD

**Issue by yoohaemin** [brarcher/budget-watch#179] opened 2018-08-26 08:53 UTC
Thanks for this great app. I found it on f-droid, and it suits my need for a lightweight expense tracker.

I'm currently staying in Japan, and the smallest amount of currency is 1 yen. Having extra two decimal points doesn't look too pretty, as I'm never going to use it.

Better yet, adding a currency per budget could solve the problem easily and be even more useful, I also have another bank account in Korea, with which I pay online subscriptions and other stuff with my debit card.

**Comment by brarcher** [comment] 2018-08-28 02:57
> I found it on f-droid, and it suits my need for a lightweight expense tracker.

Glad it is useful! (:

> Having extra two decimal points doesn't look too pretty, as I'm never going to use it.

I can see how that would be annoying, as there is no partial Yen.

Although the data for the transactions does not care if the data has a decimal place or not, the UI has encoded in a few places to use 2 decimal places as well as formatting in the US locale. That could be changed to use the current locale. That would tie back to the following issue: https://github.com/brarcher/budget-watch/issues/92. Do you agree that this is a duplicate of that?

Thanks for the suggestion. I may not be able to get to it, however if someone else were interested in contributing it I would be happy to review the changes.

**Closed** 2018-09-23 22:00 UTC
Labels: duplicate
